" === BASIC SETTINGS ===
set nocompatible
set number 
set relativenumber
set tabstop=4
set shiftwidth=4
set autoindent
set mouse=a
set showmode
set wrap
set termguicolors
syntax enable

" === LOAD PLUGINS ===
if filereadable(expand("~/.vimrc.plug"))
    source ~/.vimrc.plug
endif

" === COLORSCHEME ===
colorscheme catppuccin_mocha

" === NERDTREE SETTINGS ===
nnoremap q :NERDTreeToggle<CR>
let NERDTreeShowHidden=1
let g:NERDTreeMinimalUI=1
let g:NERDTreeDirArrows=1
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'

" === AIRLINE SETTINGS ===
let g:airline_theme='catppuccin_mocha' 
let g:airline_font=1 

" Airline extensions: tabline
let g:airline#extensions#tabline#enabled = 1
