" === BASIC SETTINGS ===
set nocompatible
set number 
set relativenumber
set tabstop=4
set shiftwidth=4
set autoindent
set mouse=a
set showmode
set wrap
set termguicolors
syntax enable

" === LOAD PLUGINS ===
if filereadable(expand("~/.vimrc.plug"))
    source ~/.vimrc.plug
endif

" === COLORSCHEME ===
colorscheme ayu

" === NERDTREE SETTINGS ===
nnoremap q :NERDTreeToggle<CR>
let NERDTreeShowHidden=1
let g:NERDTreeMinimalUI=1
let g:NERDTreeDirArrows=1
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'

" === AIRLINE SETTINGS ===
let g:airline_theme='ayu' " You can switch to 'onedark' or other themes if you prefer
let g:airline_font=1 " You can switch to 'onedark' or other themes if you prefer

" Airline extensions: tabline, branch, file info
let g:airline#extensions#tabline#enabled = 1
